export enum SkierActions {
    CARVE_LEFT = 'CARVE_LEFT',
    CARVE_RIGHT = 'CARVE_RIGHT',
    SLIDE_LEFT = 'SLIDE_LEFT',
    SLIDE_RIGHT = 'SLIDE_RIGHT',
    BRAKE = 'BRAKE',
    NOTHING = 'NOTHING'
}
