export class Config {
    // SPEED
    static MAX_SPEED = 145;

    // SLOPE
    static STANDARD_SLOPE = 10;

    // ACCELERATION
    static ACCELERATION_RATE_ON_STANDARD_SLOPE = 1;

    // CARVING
    static CARVING_ACCELERATION_RATE = 0.2;
    static CARVING_LATERAL_VELOCITY = 30;
    static CARVING_INVERTER_RATE = 2;
    static CARVING_INVERTER_VELOCITY = Config.CARVING_INVERTER_RATE * Config.CARVING_LATERAL_VELOCITY;
    static CARVING_MAX_LATERAL_VELOCITY = 1000;

    // SLIDING
    static SLIDING_ACCELERATION_RATE = -0.8;
    static SLIDING_LATERAL_VELOCITY = 3;
    static SLIDING_INVERTER_RATE = 20;
    static SLIDING_INVERTER_VELOCITY = Config.SLIDING_INVERTER_RATE * Config.SLIDING_LATERAL_VELOCITY;
    static SLIDING_MAX_VISUAL_ANGLE = 360;

}